title: 'Lente.net'
tagline: 'for Scripture &amp; Theology'

markdown: pandoc
pandoc:
  skip: true
  flags: '--smart'
  outputs:
    - pdf: '--latex-engine=xelatex'
    - markdown
    - epub
markdown: rdiscount

permalink: /:categories/:year/:month:day/:title.html